<?php 
/**
 * Defining fields for modular content
 *
 * @package Mtm_Field_Definitions
 * @author Marktime Media
 **/
class Mtm_Field_Definitions {

	// Single Content Area
	public function mtm_module_single_content_area( $label = 'Single Content Area' ) {
		return apply_filters( 'mtm_module_single_content_area_filter', array(
			'key' => '56f57790d388f',
			'name' => 'mtm_module_single_content_area',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_570bd9354d780',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f577e03cf7e',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
			'min' => '',
			'max' => '',
		));
	}


	// Dual Content Area
	public static function mtm_module_dual_content_area( $label = 'Dual Content Area' ) {
		return apply_filters( 'mtm_module_dual_content_area_filter', array(
			'key' => '56f579364c61e',
			'name' => 'mtm_module_dual_content_area',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_570bd9de4d781',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f579564c61f',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f5797e4c620',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area_2',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Content + Callout
	public static function mtm_module_content_callout( $label = 'Content + Callout' ) {
		return apply_filters( 'mtm_module_content_callout_filter', array(
			'key' => '57a203ad1549d',
			'name' => 'mtm_module_content_callout',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_57a203ad1549e',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57a203ad1549f',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
				array(
					'key' => 'field_57a203ad154a0',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area_2',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Hero Image
	public static function mtm_module_hero_image( $label = 'Hero Image' ) {
		return apply_filters( 'mtm_module_hero_image_filter', array(
			'key' => '56f57f3e501f2',
			'name' => 'mtm_module_hero_image',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_56fe9f30fa59e',
					'label' => 'Select Title',
					'name' => 'mtm_hero_select_title',
					'type' => 'radio',
					'instructions' => 'Which title should we show with this content?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Page Title' => 'Page Title',
						'Custom Headline' => 'Custom Headline',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_56f57f57501f3',
					'label' => 'Headline',
					'name' => 'mtm_hero_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56fe9f30fa59e',
								'operator' => '==',
								'value' => 'Custom Headline',
							),
						),
					),
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f580cace231',
					'label' => 'Image',
					'name' => 'mtm_hero_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_56f57f6e501f4',
					'label' => 'Subheading/Content',
					'name' => 'mtm_hero_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f57fcd501f6',
					'label' => 'Add Buttons',
					'name' => 'mtm_home_button_repeater',
					'type' => 'repeater',
					'instructions' => '(Optional) Click "Add Buttion" to add call to action buttons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_56f57fe4501f7',
							'label' => 'Button Label',
							'name' => 'mtm_home_button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57730a1ac9370',
							'label' => 'Button Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f57ffb501f8',
							'label' => 'Button Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Video/Media
	public static function mtm_module_hero_media( $label = 'Video/Media' ) {
		return apply_filters( 'mtm_module_hero_media_filter', array(
			'key' => '57813bcb6a7a1',
			'name' => 'mtm_module_hero_media',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_57813bcb6a7a2',
					'label' => 'Image, Video, or Other Content?',
					'name' => 'mtm_hero_select_media',
					'type' => 'radio',
					'instructions' => 'Add video, or other embedded content. See https://codex.wordpress.org/Embeds for what is allowed.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Video' => 'Video',
						'Other Media' => 'Other Media',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_57813bcb6a7a3',
					'label' => 'Select Title',
					'name' => 'mtm_hero_select_title',
					'type' => 'radio',
					'instructions' => 'Which title should we show with this content?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Page Title' => 'Page Title',
						'Custom Headline' => 'Custom Headline',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_57813bcb6a7a4',
					'label' => 'Headline',
					'name' => 'mtm_hero_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_57813bcb6a7a3',
								'operator' => '==',
								'value' => 'Custom Headline',
							),
						),
					),
					'wrapper' => array(
						'width' => 35,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57813bcb6a7a6',
					'label' => 'Embedded Media',
					'name' => 'mtm_hero_embed',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_57813bcb6a7a2',
								'operator' => '==',
								'value' => 'Video',
							),
						),
						array(
							array(
								'field' => 'field_57813bcb6a7a2',
								'operator' => '==',
								'value' => 'Other',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_57813bcb6a7a7',
					'label' => 'Subheading/Content',
					'name' => 'mtm_hero_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
				array(
					'key' => 'field_57813bcb6a7a8',
					'label' => 'Add Buttons',
					'name' => 'mtm_home_button_repeater',
					'type' => 'repeater',
					'instructions' => '(Optional) Click "Add Buttion" to add call to action buttons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_57813bcb6a7a9',
							'label' => 'Button Label',
							'name' => 'mtm_home_button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57813bcb6a7aa',
							'label' => 'Button Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_57813bcb6a7ab',
							'label' => 'Button Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Slider
	public static function mtm_module_slider( $label = 'Slider' ) {
		return apply_filters( 'mtm_module_slider_filter', array(
			'key' => '57815762d2d5e',
			'name' => 'mtm_module_slider',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_57815771d2d5f',
					'label' => 'Add Slides',
					'name' => 'mtm_slider_add_slides',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_578159add2d60',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Slide',
					'sub_fields' => array(
						array(
							'key' => 'field_578159add2d60',
							'label' => 'Headline',
							'name' => 'mtm_hero_headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57815a19d2d61',
							'label' => 'Subheading/Content',
							'name' => 'mtm_hero_subheading',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57815a24d2d62',
							'label' => 'Image',
							'name' => 'mtm_hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_57815a30d2d63',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_57815a65d2d64',
							'label' => 'Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Feature Boxes
	public static function mtm_module_feature_boxes( $label = 'Feature Boxes' ) {
		return apply_filters( 'mtm_module_feature_boxes_filter', array(
			'key' => '56f579d6aaafb',
			'name' => 'mtm_module_feature_boxes',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_570bd9354d799',
					'label' => 'Feature Box Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for feature boxes (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f579f9aaafc',
					'label' => 'Add Featured Content Boxes',
					'name' => 'mtm_home_featured_content_boxes',
					'type' => 'repeater',
					'instructions' => 'Click "Add Feature Box" to create a new box, then choose whether to display specific site content, the latest post from a term, or manual input',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_56f57a25aaafd',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Feature Box',
					'sub_fields' => array(
						array(
							'key' => 'field_56f57a25aaafd',
							'label' => 'Which Type Of Featured Content?',
							'name' => 'mtm_home_featured_type',
							'type' => 'radio',
							'instructions' => 'Select how you want to get content for this feature box',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Specific Content' => 'Specific Content',
								'Show Latest Post' => 'Show Latest Post',
								'Manual Entry' => 'Manual Entry',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array(
							'key' => 'field_56f57a7baaafe',
							'label' => 'Content Box Title',
							'name' => 'mtm_home_featured_box_title',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Specific Content',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Post Title' => 'Post Title',
							),
							'allow_null' => 0,
							'other_choice' => 1,
							'save_other_choice' => 0,
							'default_value' => 'Add Custom Title Here',
							'layout' => 'vertical',
						),
						array(
							'key' => 'field_56f57ab7aab00',
							'label' => 'Content Box Title',
							'name' => 'mtm_home_featured_box_manual_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_56f57aceaab01',
							'label' => 'Specific Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Specific Content',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57aeeaab02',
							'label' => 'Select Specific Content',
							'name' => 'mtm_home_featured_select_single',
							'type' => 'post_object',
							'instructions' => 'Select specific content to use as the source for your feature box',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_56f57b0aaab03',
							'label' => 'Show Latest Post',
							'name' => 'show_latest_post',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57b1faab04',
							'label' => 'Select Post Taxonomy Term',
							'name' => 'mtm_home_featured_archive_taxonomy',
							'type' => 'taxonomy-chooser',
							'instructions' => 'Use the latest post from a specific term as the content for this feature box',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'tax_type' => 0,
							'choices' => '',
							'type_value' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f57e5eaab05',
							'label' => 'Manual Content Entry',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57e76aab06',
							'label' => 'Featured Image',
							'name' => 'mtm_home_featured_image_manual',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_56f57ea0aab07',
							'label' => 'Featured Content',
							'name' => 'mtm_home_featured_content_manual',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array(
							'key' => 'field_56f57ee7aab09',
							'label' => 'Content Link',
							'name' => 'mtm_home_featured_content_link_manual',
							'type' => 'page_link',
							'instructions' => 'Link to a custom page or post on your site',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafd',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f57f03aab0a',
							'label' => 'Custom Link',
							'name' => 'mtm_home_featured_content_link_custom',
							'type' => 'text',
							'instructions' => 'If you don\'t wish to link to a page or post on your site, type your custom link here. Overrides content link.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Call To Action
	public static function mtm_module_call_to_action( $label = 'Call To Action' ) {
		return apply_filters( 'mtm_module_call_to_action_filter', array(
			'key' => '56f58e7c5bc87',
			'name' => 'mtm_module_call_to_action',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_56f58fe05bc88',
					'label' => 'Call To Action Headline',
					'name' => 'mtm_cta_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f590105bc89',
					'label' => 'Subheading/Content',
					'name' => 'mtm_cta_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f5902f5bc8a',
					'label' => 'CTA Buttons',
					'name' => 'mtm_cta_button_repeater',
					'type' => 'repeater',
					'instructions' => 'Click "Add Button" to add call to action buttons that will lead to other pages, other sections within a page, or elsewhere.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_56f5904a5bc8b',
							'label' => 'CTA Button Label',
							'name' => 'mtm_cta_button_label',
							'type' => 'text',
							'instructions' => 'The text that will show up on your call to action button',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57730910c936f',
							'label' => 'CTA Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f590765bc8c',
							'label' => 'CTA Button Link',
							'name' => 'mtm_cta_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to an anchor tag on the same page, or a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Logo/Graphic Showcase
	public static function mtm_module_logo_showcase( $label = 'Logo/Graphic Showcase' ) {
		return apply_filters( 'mtm_module_logo_showcase_filter', array(
			'key' => '56f59482418ef',
			'name' => 'mtm_module_logo_showcase',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_56feb088a4a16',
					'label' => 'Logo/Graphic Area Title',
					'name' => 'mtm_logo_title',
					'type' => 'text',
					'instructions' => 'Optional title for the logo/graphic area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f59494418f0',
					'label' => 'Add Logo/Graphic',
					'name' => 'mtm_logo_repeater',
					'type' => 'repeater',
					'instructions' => 'Click "Add Logo" to add a logo/graphic showcase to your page (transparent PNG images preferred for logos)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_56f594e1418f1',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Logo',
					'sub_fields' => array(
						array(
							'key' => 'field_56f594e1418f1',
							'label' => 'Logo/Graphic',
							'name' => 'mtm_logo_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5773089ac936e',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f594fd418f2',
							'label' => 'Custom Link',
							'name' => 'mtm_logo_link',
							'type' => 'text',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Widget Area
	public static function mtm_module_widget_area( $label = 'Widget Area' ) {
		return apply_filters( 'mtm_module_widget_area_filter', array(
			'key' => '570bd7f0a52c7',
			'name' => 'mtm_module_widget_area',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_570bd7fba52c8',
					'label' => 'Widget Area Title',
					'name' => 'mtm_widget_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for widget area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_570bd811a52c9',
					'label' => 'Select Widget Area',
					'name' => 'mtm_select_widget_area',
					'type' => 'widget_area',
					'instructions' => 'Select which widget area to show. You can add widgets to this area under Appearance > Widgets.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_null' => 1,
					'display_or_return' => 'return',
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Manual List
	public static function mtm_module_listgrid( $label = 'Manual List' ) {
		return apply_filters( 'mtm_module_listgrid_filter', array(
			'key' => '5728d653cf63f',
			'name' => 'mtm_module_listgrid',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5728dc4b35580',
					'label' => 'List Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for list area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5728d666cf640',
					'label' => 'Add List Item',
					'name' => 'mtm_add_list_item',
					'type' => 'repeater',
					'instructions' => 'Click "Add List Item" to create a new list row',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5728d690cf641',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add List Item',
					'sub_fields' => array(
						array(
							'key' => 'field_5728d690cf641',
							'label' => 'Heading',
							'name' => 'mtm_list_item_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_5772ff2b7839e',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5728eaf86b3ca',
							'label' => 'Custom Link',
							'name' => 'mtm_list_item_link',
							'type' => 'url',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5728d6b0cf642',
							'label' => 'Content',
							'name' => 'mtm_list_item_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57730099184bd',
							'label' => 'File (optional)',
							'name' => 'mtm_list_item_file',
							'type' => 'file',
							'instructions' => 'Include a file with this list item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5728d6c7cf643',
							'label' => 'Image (optional)',
							'name' => 'mtm_list_item_image',
							'type' => 'image',
							'instructions' => 'Include an image with this list item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Manual Grid
	public static function mtm_module_gridlist( $label = 'Manual Grid' ) {
		return apply_filters( 'mtm_module_gridlist_filter', array(
			'key' => '576a88e224ba2',
			'name' => 'mtm_module_gridlist',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_576a88e224ba3',
					'label' => 'Grid Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for grid area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_576bec54e5801',
					'label' => 'Number of Items Per Row?',
					'name' => 'mtm_grid_archive_per_row',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 6,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_576a88e224ba8',
					'label' => 'Add Grid Item',
					'name' => 'mtm_add_list_item',
					'type' => 'repeater',
					'instructions' => 'Click "Add Grid Item" to create a new Grid block',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_576a88e224ba9',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Grid Item',
					'sub_fields' => array(
						array(
							'key' => 'field_576a88e224ba9',
							'label' => 'Heading',
							'name' => 'mtm_list_item_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_5773000c184bb',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_576a88e224baa',
							'label' => 'Custom Link',
							'name' => 'mtm_list_item_link',
							'type' => 'url',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_576a88e224bab',
							'label' => 'Content',
							'name' => 'mtm_list_item_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57730067184bc',
							'label' => 'File (optional)',
							'name' => 'mtm_list_item_file',
							'type' => 'file',
							'instructions' => 'Include a file with this grid item',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_576a88e224bac',
							'label' => 'Image (optional)',
							'name' => 'mtm_list_item_image',
							'type' => 'image',
							'instructions' => 'Include an image with this grid item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Post List
	public static function mtm_module_listgrid_posts( $label = 'Post List' ) {
		return apply_filters( 'mtm_module_listgrid_posts_filter', array(
			'key' => '5783de4c38883',
			'name' => 'mtm_module_listgrid_posts',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5783de4c38884',
					'label' => 'List Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for list area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de4c38885',
					'label' => 'Content Source',
					'name' => 'mtm_list_archive_select',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Add Posts Manually' => 'Add Posts Manually',
						'Pick From Taxonomy' => 'Pick From Taxonomy',
						'Pick From Post Type' => 'Pick From Post Type',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_5783de4c38886',
					'label' => 'Select Source',
					'name' => 'mtm_list_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5783de4c38887',
					'label' => 'Select Post Type',
					'name' => 'mtm_list_archive_post_type',
					'type' => 'post_type_selector',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'select_type' => 0,
				),
				array(
					'key' => 'field_5783e66e808c7',
					'label' => 'Select Content',
					'name' => 'mtm_list_archive_manual_posts',
					'type' => 'relationship',
					'instructions' => 'Add and reorder content to build your list. Use the search and filters to narrow down your selection.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Add Posts Manually',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'filters' => array(
						0 => 'search',
						1 => 'post_type',
						2 => 'taxonomy',
					),
					'elements' => array (
						0 => 'featured_image',
					),
					'min' => '',
					'max' => '',
					'return_format' => 'object',
				),
				array(
					'key' => 'field_5783de4c38888',
					'label' => 'Total Number of Items?',
					'name' => 'mtm_list_archive_taxonomy_number',
					'type' => 'number',
					'instructions' => 'How many total items do you want to display in this list?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783e5d7808c5',
					'label' => 'Show Taxonomy Links?',
					'name' => 'mtm_show_taxonomy_links',
					'type' => 'true_false',
					'instructions' => 'Do you want to show a list of terms to use as links/filters?',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783e637808c6',
					'label' => 'Which Taxonomy?',
					'name' => 'mtm_list_archive_taxonomy_links',
					'type' => 'taxonomy-chooser',
					'instructions' => 'Which taxonomy should we select to display the terms?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783e5d7808c5',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 1,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_578f8e190874f',
					'label' => 'Show "View All" Link?',
					'name' => 'mtm_show_view_all_link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de4c38885',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Yes, add a "View All" link to the bottom of this list',
					'default_value' => 0,
				),
				array(
					'key' => 'field_57835e9283ur9834bb',
					'label' => 'View All Link Text',
					'name' => 'mtm_view_all_link_text',
					'type' => 'text',
					'instructions' => 'Optional text for Veiw All link',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_578f8e190874f',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Post Grid
	public static function mtm_module_gridlist_posts( $label = 'Post Grid' ) {
		return apply_filters( 'mtm_module_gridlist_posts_filter', array(
			'key' => '5783de5e38890',
			'name' => 'mtm_module_gridlist_posts',
			'label' => $label,
			'display' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5783de5e38891',
					'label' => 'Grid Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for grid area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de5e38896',
					'label' => 'Number of Items Per Row?',
					'name' => 'mtm_grid_archive_per_row',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 6,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de5e38892',
					'label' => 'Content Source',
					'name' => 'mtm_list_archive_select',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Add Posts Manually' => 'Add Posts Manually',
						'Pick From Taxonomy' => 'Pick From Taxonomy',
						'Pick From Post Type' => 'Pick From Post Type',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_5783de5e38893',
					'label' => 'Select Source',
					'name' => 'mtm_list_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5783de5e38894',
					'label' => 'Select Post Type',
					'name' => 'mtm_list_archive_post_type',
					'type' => 'post_type_selector',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'select_type' => 0,
				),
				array(
					'key' => 'field_5783dee83889e',
					'label' => 'Select Content',
					'name' => 'mtm_list_archive_manual_posts',
					'type' => 'relationship',
					'instructions' => 'Add and reorder content to build your grid. Use the search and filters to narrow down your selection.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Add Posts Manually',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'filters' => array(
						0 => 'search',
						1 => 'post_type',
						2 => 'taxonomy',
					),
					'elements' => array (
						0 => 'featured_image',
					),
					'min' => '',
					'max' => '',
					'return_format' => 'object',
				),
				array(
					'key' => 'field_5783de5e38895',
					'label' => 'Total Number of Items?',
					'name' => 'mtm_list_archive_taxonomy_number',
					'type' => 'number',
					'instructions' => 'How many total items do you want to display in this grid?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783dfaa3889f',
					'label' => 'Show Taxonomy Links?',
					'name' => 'mtm_show_taxonomy_links',
					'type' => 'true_false',
					'instructions' => 'Do you want to show a list of terms to use as links/filters?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783e0e0388a0',
					'label' => 'Which Taxonomy?',
					'name' => 'mtm_list_archive_taxonomy_links',
					'type' => 'taxonomy-chooser',
					'instructions' => 'Which taxonomy should we select to display the terms?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783dfaa3889f',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 1,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_578f8e4208750',
					'label' => 'Show "View All" link?',
					'name' => 'mtm_show_view_all_link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Yes, add a "View All" link to the bottom of this grid',
					'default_value' => 0,
				),
				array(
					'key' => 'field_57835e9283ur9834',
					'label' => 'View All Link Text',
					'name' => 'mtm_view_all_link_text',
					'type' => 'text',
					'instructions' => 'Optional text for Veiw All link',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_578f8e4208750',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => '',
			'max' => '',
		));
	}

	// Show Page Title?
	public static function mtm_module_show_page_title( $label = 'Show Page Title?' ) {
		return apply_filters( 'mtm_module_show_page_title_filter', array(
			'key' => 'field_570c0e236b517',
			'label' => $label,
			'name' => 'mtm_module_show_page_title',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, show the page title at the top of the page (unchecking this will hide the page title)',
			'default_value' => 0,
		));
	}

} // END class 