<?php 

// Registers all ACF fields
// Un-inlcude this file and import the JSON file to make changes to the fields, then re-export field data

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_565cb5e35a2af',
	'title' => 'Components',
	'fields' => array (
		array (
			'key' => 'field_565cb6189bf5c',
			'label' => 'Select Component',
			'name' => 'mtm_select_component',
			'type' => 'radio',
			'instructions' => 'Select which type of component page we are creating',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Standard Content' => 'Standard Content',
				'List Archive' => 'List Archive',
				'Grid Archive' => 'Grid Archive',
				'Tabs' => 'Tabs',
				'Call To Action' => 'Call To Action',
				'Extra Content' => 'Extra Content',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_565cb75b8c1af',
			'label' => 'List Archive',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565cbc594ae15',
			'label' => 'Select List Source',
			'name' => 'mtm_list_archive_select',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Pick From Taxonomy' => 'Pick From Taxonomy',
				'Pick Manually' => 'Pick Manually',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_565cce669fa4b',
			'label' => 'Taxonomy Term List Selection',
			'name' => 'mtm_list_archive_taxonomy',
			'type' => 'taxonomy-chooser',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cbc594ae15',
						'operator' => '==',
						'value' => 'Pick From Taxonomy',
					),
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tax_type' => 0,
			'choices' => '',
			'type_value' => 1,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_565cd42965450',
			'label' => 'Number of Items to Display',
			'name' => 'mtm_list_archive_taxonomy_number',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cbc594ae15',
						'operator' => '==',
						'value' => 'Pick From Taxonomy',
					),
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565cbcf34ae16',
			'label' => 'Manual List Selection',
			'name' => 'mtm_list_archive_manual',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cbc594ae15',
						'operator' => '==',
						'value' => 'Pick Manually',
					),
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => 1,
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_565cb92c8c1b0',
			'label' => 'Tabs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Tabs',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565cd5c57dc40',
			'label' => 'Add Tabs',
			'name' => 'mtm_tab_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_565cd5e07dc41',
					'label' => 'Tab Title',
					'name' => 'mtm_tab_title',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_565cd5f07dc42',
					'label' => 'Tab Content',
					'name' => 'mtm_tab_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
		),
		array (
			'key' => 'field_565cb9d48c1b1',
			'label' => 'Grid Archive',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Grid Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565cd752f6e89',
			'label' => 'Select Grid Source',
			'name' => 'mtm_grid_archive_select',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Pick From Taxonomy' => 'Pick From Taxonomy',
				'Pick Manually' => 'Pick Manually',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_565cd760f6e8a',
			'label' => 'Taxonomy Term Grid Selection',
			'name' => 'mtm_grid_archive_taxonomy',
			'type' => 'taxonomy-chooser',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cd752f6e89',
						'operator' => '==',
						'value' => 'Pick From Taxonomy',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tax_type' => 0,
			'choices' => '',
			'type_value' => 1,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_565cd76bf6e8b',
			'label' => 'Number of Items to Display',
			'name' => 'mtm_grid_archive_taxonomy_number',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cd752f6e89',
						'operator' => '==',
						'value' => 'Pick From Taxonomy',
					),
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Grid Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565cd79af6e8c',
			'label' => 'Manual Grid Selection',
			'name' => 'mtm_grid_archive_manual',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cd752f6e89',
						'operator' => '==',
						'value' => 'Pick Manually',
					),
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Grid Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => 1,
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_567b01bba3b64',
			'label' => 'Taxonomy List',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Grid Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565cd847f6e8d',
			'label' => 'Show Taxonomy Links',
			'name' => 'mtm_show_taxonomy_links',
			'type' => 'true_false',
			'instructions' => 'Show a list of all terms which link to their respective archives',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Grid Archive',
					),
				),
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'List Archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_567af5c064029',
			'label' => 'Select Taxonomy Links Source',
			'name' => 'mtm_manual_archive_taxonomy',
			'type' => 'taxonomy-chooser',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cbc594ae15',
						'operator' => '==',
						'value' => 'Pick Manually',
					),
					array (
						'field' => 'field_565cd847f6e8d',
						'operator' => '==',
						'value' => '1',
					),
				),
				array (
					array (
						'field' => 'field_565cd847f6e8d',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_565cd752f6e89',
						'operator' => '==',
						'value' => 'Pick Manually',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tax_type' => 1,
			'choices' => '',
			'type_value' => 1,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_56a25f4f148a3',
			'label' => 'Call To Action',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Call To Action',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56a260b5148a6',
			'label' => 'CTA Buttons',
			'name' => 'mtm_cta_button_repeater',
			'type' => 'repeater',
			'instructions' => 'Add call to action buttons that will lead to other pages, other sections within a page, or elsewhere.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Call To Action',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56a25f61148a4',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Button',
			'sub_fields' => array (
				array (
					'key' => 'field_56a25f61148a4',
					'label' => 'CTA Button Label',
					'name' => 'mtm_cta_button_label',
					'type' => 'text',
					'instructions' => 'The text that will show up on your call to action button',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56a2603e148a5',
					'label' => 'CTA Button Link',
					'name' => 'mtm_cta_button_link',
					'type' => 'text',
					'instructions' => 'URL destination of your button (such as another page within your site, an anchor tag on the same page, or somewhere else)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_5685b18361f65',
			'label' => 'Extra Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Extra Content',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5685b19061f66',
			'label' => 'Extra Content Area',
			'name' => 'mtm_extra_content_area',
			'type' => 'wysiwyg',
			'instructions' => 'Use this to add a form, videos, or other content you want separated from the main content area',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565cb6189bf5c',
						'operator' => '==',
						'value' => 'Extra Content',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'component',
				'operator' => '==',
				'value' => '../templates/template-components.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56f5752dccdbf',
	'title' => 'Content Modules',
	'fields' => array (
		array (
			'key' => 'field_570c0e236b517',
			'label' => 'Show Page Title?',
			'name' => 'mtm_module_show_page_title',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, show the page title at the top of the page (unchecking this will hide the page title)',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56f5778adcb85',
			'label' => 'Add Content Modules',
			'name' => 'mtm_content_modules',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Content Area',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '56f57790d388f',
					'name' => 'mtm_module_single_content_area',
					'label' => 'Single Content Area',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_570bd9354d780',
							'label' => 'Content Area Title',
							'name' => 'mtm_text_area_title',
							'type' => 'text',
							'instructions' => 'Optional title for content area (leave blank for no title)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56f577e03cf7e',
							'label' => 'Content Area',
							'name' => 'mtm_module_text_area',
							'type' => 'wysiwyg',
							'instructions' => 'Add text, images, links, forms, or shortcodes',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56f579364c61e',
					'name' => 'mtm_module_dual_content_area',
					'label' => 'Dual Content Area',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_570bd9de4d781',
							'label' => 'Content Area Title',
							'name' => 'mtm_text_area_title',
							'type' => 'text',
							'instructions' => 'Optional title for content area (leave blank for no title)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56f579564c61f',
							'label' => 'Content Area',
							'name' => 'mtm_module_text_area',
							'type' => 'wysiwyg',
							'instructions' => 'Add text, images, links, forms, or shortcodes',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56f5797e4c620',
							'label' => 'Content Area',
							'name' => 'mtm_module_text_area_2',
							'type' => 'wysiwyg',
							'instructions' => 'Add text, images, links, forms, or shortcodes',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56f57f3e501f2',
					'name' => 'mtm_module_hero_image',
					'label' => 'Hero Image/Video',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56f5816dce232',
							'label' => 'Image, Video, or Other Content?',
							'name' => 'mtm_hero_select_media',
							'type' => 'radio',
							'instructions' => 'Add a hero image, video, or other embedded content. See https://codex.wordpress.org/Embeds for what is allowed.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Image' => 'Image',
								'Video' => 'Video',
								'Other' => 'Other',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array (
							'key' => 'field_56fe9f30fa59e',
							'label' => 'Select Title',
							'name' => 'mtm_hero_select_title',
							'type' => 'radio',
							'instructions' => 'Which title should we show with this content?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Page Title' => 'Page Title',
								'Custom Headline' => 'Custom Headline',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array (
							'key' => 'field_56f57f57501f3',
							'label' => 'Headline',
							'name' => 'mtm_hero_headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56fe9f30fa59e',
										'operator' => '==',
										'value' => 'Custom Headline',
									),
								),
							),
							'wrapper' => array (
								'width' => 35,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56f580cace231',
							'label' => 'Image',
							'name' => 'mtm_hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56f5816dce232',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56f581a8ce233',
							'label' => 'Embedded Media',
							'name' => 'mtm_hero_embed',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56f5816dce232',
										'operator' => '==',
										'value' => 'Video',
									),
								),
								array (
									array (
										'field' => 'field_56f5816dce232',
										'operator' => '==',
										'value' => 'Other',
									),
								),
							),
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
						array (
							'key' => 'field_56f57f6e501f4',
							'label' => 'Subheading/Content',
							'name' => 'mtm_hero_subheading',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_56f57fcd501f6',
							'label' => 'Add Buttons',
							'name' => 'mtm_home_button_repeater',
							'type' => 'repeater',
							'instructions' => '(Optional) Add call to action buttons',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Button',
							'sub_fields' => array (
								array (
									'key' => 'field_56f57fe4501f7',
									'label' => 'Button Label',
									'name' => 'mtm_home_button_label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56f57ffb501f8',
									'label' => 'Button Link',
									'name' => 'mtm_home_button_link',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56f579d6aaafb',
					'name' => 'mtm_module_feature_boxes',
					'label' => 'Feature Boxes',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56f579f9aaafc',
							'label' => 'Add Featured Content Boxes',
							'name' => 'mtm_home_featured_content_boxes',
							'type' => 'repeater',
							'instructions' => 'Set featured content boxes from a specific piece of content, the latest post, or manual input',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_56f57a25aaafd',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Feature Box',
							'sub_fields' => array (
								array (
									'key' => 'field_56f57a25aaafd',
									'label' => 'Which Type Of Featured Content?',
									'name' => 'mtm_home_featured_type',
									'type' => 'radio',
									'instructions' => 'Select the type of featured content you want this to be',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'Specific Content' => 'Specific Content',
										'Show Latest Post' => 'Show Latest Post',
										'Manual Entry' => 'Manual Entry',
									),
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
								),
								array (
									'key' => 'field_56f57a7baaafe',
									'label' => 'Content Box Title',
									'name' => 'mtm_home_featured_box_title',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Show Latest Post',
											),
										),
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Specific Content',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'Post Title' => 'Post Title',
									),
									'other_choice' => 1,
									'save_other_choice' => 0,
									'default_value' => 'Add Custom Title Here',
									'layout' => 'vertical',
								),
								array (
									'key' => 'field_56f57ab7aab00',
									'label' => 'Content Box Title',
									'name' => 'mtm_home_featured_box_manual_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Manual Entry',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56f57aceaab01',
									'label' => 'Specific Content',
									'name' => 'specific_content',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Specific Content',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array (
									'key' => 'field_56f57aeeaab02',
									'label' => 'Select Specific Content',
									'name' => 'mtm_home_featured_select_single',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array (
									'key' => 'field_56f57b0aaab03',
									'label' => 'Show Latest Post',
									'name' => 'show_latest_post',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Show Latest Post',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array (
									'key' => 'field_56f57b1faab04',
									'label' => 'Select Post Taxonomy',
									'name' => 'mtm_home_featured_archive_taxonomy',
									'type' => 'taxonomy-chooser',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Show Latest Post',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'tax_type' => 0,
									'choices' => '',
									'type_value' => 1,
									'allow_null' => 0,
									'ui' => 0,
									'ajax' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_56f57e5eaab05',
									'label' => 'Manual Content Entry',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Manual Entry',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array (
									'key' => 'field_56f57e76aab06',
									'label' => 'Featured Image',
									'name' => 'mtm_home_featured_image_manual',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Manual Entry',
											),
										),
									),
									'wrapper' => array (
										'width' => 40,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56f57ea0aab07',
									'label' => 'Box Content',
									'name' => 'mtm_home_featured_content_manual',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Manual Entry',
											),
										),
									),
									'wrapper' => array (
										'width' => 60,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 0,
								),
								array (
									'key' => 'field_56f57ee7aab09',
									'label' => 'Content Link',
									'name' => 'mtm_home_featured_content_link_manual',
									'type' => 'page_link',
									'instructions' => 'Link to a custom page or post on your site',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56f57a25aaafd',
												'operator' => '==',
												'value' => 'Manual Entry',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_56f57f03aab0a',
									'label' => 'Custom Link',
									'name' => 'mtm_home_featured_content_link_custom',
									'type' => 'text',
									'instructions' => 'If you don\'t wish to link to a page or post on your site, type your custom link here. Overrides content link.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56f58e7c5bc87',
					'name' => 'mtm_module_call_to_action',
					'label' => 'Call To Action',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56f58fe05bc88',
							'label' => 'Call To Action Headline',
							'name' => 'mtm_cta_headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56f590105bc89',
							'label' => 'Subheading/Content',
							'name' => 'mtm_cta_subheading',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56f5902f5bc8a',
							'label' => 'CTA Buttons',
							'name' => 'mtm_cta_button_repeater',
							'type' => 'repeater',
							'instructions' => 'Add call to action buttons that will lead to other pages, other sections within a page, or elsewhere.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'button_label' => 'Add Button',
							'layout' => 'table',
							'sub_fields' => array (
								array (
									'key' => 'field_56f5904a5bc8b',
									'label' => 'CTA Button Label',
									'name' => 'mtm_cta_button_label',
									'type' => 'text',
									'instructions' => 'The text that will show up on your call to action button',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56f590765bc8c',
									'label' => 'CTA Button Link',
									'name' => 'mtm_cta_button_link',
									'type' => 'text',
									'instructions' => 'URL destination of your button (such as another page within your site, an anchor tag on the same page, or somewhere else)',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56f59482418ef',
					'name' => 'mtm_module_logo_showcase',
					'label' => 'Logo Showcase',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56feb088a4a16',
							'label' => 'Logo Area Title',
							'name' => 'mtm_logo_title',
							'type' => 'text',
							'instructions' => 'Optional title for the logo showcase (leave blank for no title)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56f59494418f0',
							'label' => 'Add Logo/Graphic',
							'name' => 'mtm_logo_repeater',
							'type' => 'repeater',
							'instructions' => 'Add a logo showcase to your page (transparent PNG images preferred)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_56f594e1418f1',
							'min' => '',
							'max' => '',
							'button_label' => 'Add Logo',
							'layout' => 'table',
							'sub_fields' => array (
								array (
									'key' => 'field_56f594e1418f1',
									'label' => 'Logo',
									'name' => 'mtm_logo_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 40,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56f594fd418f2',
									'label' => 'Link',
									'name' => 'mtm_logo_link',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 60,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56fe83ceed116',
					'name' => 'mtm_module_gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56fe83dbed117',
							'label' => 'Select Gallery Source',
							'name' => 'mtm_select_post_source',
							'type' => 'post_object',
							'instructions' => 'Select which gallery post you would like to use',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'post',
								1 => 'page',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array (
							'key' => 'field_56fe8cd4a8482',
							'label' => 'Show Title of Gallery?',
							'name' => 'mtm_post_source_title',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Yes, show the title',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '570bd7f0a52c7',
					'name' => 'mtm_module_widget_area',
					'label' => 'Widget Area',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_570bd7fba52c8',
							'label' => 'Widget Area Title',
							'name' => 'mtm_widget_area_title',
							'type' => 'text',
							'instructions' => 'Optional title for widget area (leave blank for no title)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_570bd811a52c9',
							'label' => 'Select Widget Area',
							'name' => 'mtm_select_widget_area',
							'type' => 'widget_area',
							'instructions' => 'Select which widget area to show. You can add widgets to this area under Appearance > Widgets.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'allow_null' => 1,
							'display_or_return' => 'return',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5728d653cf63f',
					'name' => 'mtm_module_listgrid',
					'label' => 'List/Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5728dc4b35580',
							'label' => 'List Title',
							'name' => 'mtm_list_title',
							'type' => 'text',
							'instructions' => 'Optional title for list/grid	(leave blank for no title)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5728d783cf644',
							'label' => 'List or Grid?',
							'name' => 'mtm_select_list_or_grid',
							'type' => 'radio',
							'instructions' => 'Choose whether to display these items as a list or a grid',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'List' => 'List',
								'Grid' => 'Grid',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array (
							'key' => 'field_5728d666cf640',
							'label' => 'Add List Item',
							'name' => 'mtm_add_list_item',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5728d690cf641',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add List Item',
							'sub_fields' => array (
								array (
									'key' => 'field_5728d690cf641',
									'label' => 'Heading',
									'name' => 'mtm_list_item_heading',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_5728d6b0cf642',
									'label' => 'Content',
									'name' => 'mtm_list_item_content',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 66,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 1,
								),
								array (
									'key' => 'field_5728d6c7cf643',
									'label' => 'Image',
									'name' => 'mtm_list_item_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 33,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'component',
				'operator' => '==',
				'value' => '../templates/template-modules.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565cdb18b4c4c',
	'title' => 'Landing Page Content Options',
	'fields' => array (
		array (
			'key' => 'field_56bcbd02ab424',
			'label' => 'Landing Page Type',
			'name' => 'mtm_homepage_type',
			'type' => 'radio',
			'instructions' => 'Select which type of landing page you are building',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'mtm-homepage-type-field',
				'id' => '',
			),
			'choices' => array (
				'Standard' => 'Standard',
				'News' => 'News',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_565e2f81c08ca',
			'label' => 'Enable Single Scroll Page?',
			'name' => 'mtm_enable_single_scroll_page',
			'type' => 'true_false',
			'instructions' => 'This will enable you to build a long, "single scroll" style page using other pages on your site',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, I would like to show other page content underneath the landing page content',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56bcbd4fab425',
			'label' => 'Standard Landing Page Options',
			'name' => 'standard_landing_page_options',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56bcbd02ab424',
						'operator' => '==',
						'value' => 'Standard',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565cdb25b1d30',
			'label' => 'Add Buttons',
			'name' => 'mtm_home_button_repeater',
			'type' => 'repeater',
			'instructions' => '(Optional) Add call to action buttons to the main landing page area',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Button',
			'sub_fields' => array (
				array (
					'key' => 'field_565cdb44b1d31',
					'label' => 'Button Label',
					'name' => 'mtm_home_button_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_565cdb53b1d32',
					'label' => 'Button Link',
					'name' => 'mtm_home_button_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_568314207680d',
			'label' => 'Enable Featured Content Boxes?',
			'name' => 'mtm_enable_featured_content',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, show Featured Content Boxes on the landing page',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56830bcd85f0e',
			'label' => 'Add Featured Content Boxes',
			'name' => 'mtm_home_featured_content_boxes',
			'type' => 'repeater',
			'instructions' => '(Optional) Add featured content boxes to the homepage',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_568314207680d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56830c0e85f0f',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Flexible Content Box',
			'sub_fields' => array (
				array (
					'key' => 'field_56830c0e85f0f',
					'label' => 'Which Type Of Featured Content?',
					'name' => 'mtm_home_featured_type',
					'type' => 'radio',
					'instructions' => 'Select the type of featured content you want this to be',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Specific Content' => 'Specific Content',
						'Show Latest Post' => 'Show Latest Post',
						'Manual Entry' => 'Manual Entry',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_56830ef012152',
					'label' => 'Content Box Title',
					'name' => 'mtm_home_featured_box_title',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Show Latest Post',
							),
						),
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Specific Content',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Post Title' => 'Post Title',
					),
					'other_choice' => 1,
					'save_other_choice' => 0,
					'default_value' => 'Add Custom Title Here',
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_568311abdbeb9',
					'label' => 'Content Box Title',
					'name' => 'mtm_home_featured_box_manual_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Manual Entry',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56830cc085f10',
					'label' => 'Specific Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Specific Content',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5683104bf206d',
					'label' => 'Select Specific Content',
					'name' => 'mtm_home_featured_select_single',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_56830cfe85f11',
					'label' => 'Show Latest Post',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Show Latest Post',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_56830e9a12151',
					'label' => 'Select Post Taxonomy',
					'name' => 'mtm_home_featured_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Show Latest Post',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_56830d0d85f12',
					'label' => 'Manual Content Entry',
					'name' => 'manual_content_entry',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Manual Entry',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_568311f6dbeba',
					'label' => 'Featured Image',
					'name' => 'mtm_home_featured_image_manual',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Manual Entry',
							),
						),
					),
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5683123edbebb',
					'label' => 'Box Content',
					'name' => 'mtm_home_featured_content_manual',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Manual Entry',
							),
						),
					),
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
				array (
					'key' => 'field_5683127cdbebc',
					'label' => 'Content Link',
					'name' => 'mtm_home_featured_content_link_manual',
					'type' => 'page_link',
					'instructions' => 'Link to a custom page or post on your site',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56830c0e85f0f',
								'operator' => '==',
								'value' => 'Manual Entry',
							),
						),
					),
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_56a7cbed3e0cd',
					'label' => 'Custom Link',
					'name' => 'mtm_home_featured_content_link_custom',
					'type' => 'text',
					'instructions' => 'If you don\'t wish to link to a page or post on your site, type your custom link here. Overrides content link.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56bcbd7fab426',
			'label' => 'News Landing Page Options',
			'name' => 'news_landing_page_options',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56bcbd02ab424',
						'operator' => '==',
						'value' => 'News',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_570c11068a259',
			'label' => 'Show Page Title?',
			'name' => 'mtm_news_show_page_title',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Yes, I\'d like to show the page title at the top of the page (leaving unchecked will hide the page title)',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56bcbe7315d31',
			'label' => 'Select Featured Story Source',
			'name' => 'mtm_home_select_featured_story_source',
			'type' => 'select',
			'instructions' => 'Select the source for your featured story, which will display at the top of the page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Latest Post' => 'Latest Post',
				'Latest Post From Taxonomy' => 'Latest Post From Taxonomy',
				'Specific Post' => 'Specific Post',
				'No Featured Story' => 'No Featured Story',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_571011a354604',
			'label' => 'Which Post Type?',
			'name' => 'mtm_home_select_featured_story_type',
			'type' => 'post_type_selector',
			'instructions' => 'Choose which post type will be the source for your featured story.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56bcbe7315d31',
						'operator' => '==',
						'value' => 'Latest Post',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'fields[mtm_home_select_featured_story_type' => array (
				'select_type' => 1,
			),
			'select_type' => 0,
		),
		array (
			'key' => 'field_56bcbf7315d35',
			'label' => 'Featured Story Topic',
			'name' => 'mtm_home_featured_story_archive_taxonomy',
			'type' => 'taxonomy-chooser',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56bcbe7315d31',
						'operator' => '==',
						'value' => 'Latest Post From Taxonomy',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'tax_type' => 0,
			'choices' => '',
			'type_value' => 1,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_56bcbfcb15d36',
			'label' => 'Featured Story Specific Post',
			'name' => 'mtm_home_featured_story_select_single',
			'type' => 'post_object',
			'instructions' => 'Select which post will be featured on the landing page. This will remain until you change it.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56bcbe7315d31',
						'operator' => '==',
						'value' => 'Specific Post',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_56bcc3f74badb',
			'label' => 'Add Topic Sections',
			'name' => 'mtm_home_topic_sections',
			'type' => 'repeater',
			'instructions' => 'Optional: Add and reorder topic sections which will display on the landing page, below your featured story',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Topic',
			'sub_fields' => array (
				array (
					'key' => 'field_56bcc44d4badc',
					'label' => 'Topics',
					'name' => 'mtm_home_topic_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
			),
		),
		array (
			'key' => 'field_56bcc2e64bada',
			'label' => 'How Many Stories Per Topic?',
			'name' => 'mtm_home_stories_per_topic',
			'type' => 'number',
			'instructions' => 'How many stories to list in each topic, including the main story?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => 4,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56bcbdcb85f77',
			'label' => 'Single Scroll Page Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565e2f81c08ca',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565e2fa2c08cb',
			'label' => 'Select Pages',
			'name' => 'mtm_select_pages',
			'type' => 'relationship',
			'instructions' => 'Select and re-order page content which will display in sections on your landing page, below the main content. To make sure special features are enabled, make sure your selected pages are using the Page Components template.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565e2f81c08ca',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'component',
				'operator' => '==',
				'value' => '../templates/template-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56831a6c39e46',
	'title' => 'Background Image',
	'fields' => array (
		array (
			'key' => 'field_565cdb92e45d7',
			'label' => 'Add Background Image',
			'name' => 'mtm_home_background_image',
			'type' => 'image',
			'instructions' => '(Optional) Add a background image to the homepage area',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'component',
				'operator' => '==',
				'value' => '../templates/template-home.php',
			),
		),
	),
	'menu_order' => 100,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;